defaults: &defaults
  base_uri: 'http://api.sponsorpay.com'
  prefix: 'feed'
  version: 'v1'
  api_key: 'b07a12df7d52e6c118e5d47d3f9e60135b109a1f'
  open_timeout: 2
  read_timeout: 5

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults